export const colors = [
  {
    name: "Yellow",
    background: "#fbe9ba",
    btn: "#F4C550",
    image: "../images/iMac/iMac=Yellow.svg",
    activeStyle: "#F4C550",
  },
  {
    name: "Green",
    background: "#cbded3",
    btn: "#9FBAAE",
    image: "../images/iMac/iMac=Green.svg",
    activeStyle: "#9FBAAE",
  },
  {
    name: "Blue",
    background: "#bfd6ea",
    btn: "#9FB7CE",
    image: "../images/iMac/iMac=Blue.svg",
    activeStyle: "#9FB7CE",
  },
  {
    name: "Red",
    background: "#F2C0BD",
    btn: "#E0A39A",
    image: "../images/iMac/iMac = Red.svg",
    activeStyle: "#E0A39A",
  },
  {
    name: "Orange",
    background: "#F4C8BA",
    btn: "#F0AA8D",
    image: "../images/iMac",
    activeStyle: "#F0AA8D",
  },
  {
    name: "Blue",
    background: "#95C7F2",
    btn: "#4499EB",
    image: "../images/iMac/iMac=Blue.svg",
    activeStyle: "#4499EB",
  },
  {
    name: "Yellow",
    background: "#E9E6AB",
    btn: "#EEE73B",
    image: "../images/iMac/iMac=Yellow.svg",
    activeStyle: "#EEE73B",
  },
  {
    name: "Green",
    background: "#AEF0CA",
    btn: "#31E997",
    image: "../images/iMac/iMac=Green.svg",
    activeStyle: "#31E997",
  },
  {
    name: "Red",
    background: "#F67F7F",
    btn: "#F61515",
    image: "../images/iMac/iMac = Red.svg",
    activeStyle: "#F61515",
  },
];
